<?php
	// Temporary root.
	$rootpath = str_replace("\\", "/", dirname(__FILE__));
	require_once $rootpath . "/../support/webroute.php";

	$wr = new WebRoute();

	// The ID sent by two clients should be a string generated by a CSPRNG.
	// This is static so that the test will succeed.
	$id = "6fa1a1490ee0fe617b36530054e984786897e022";

	// Connect to the WebRoute server with the static ID.
	$result = $wr->Connect("wr://127.0.0.1:47735/test?accesskey=123456789101112", $id);
	if (!$result["success"])
	{
		var_dump($result);
		exit();
	}

	// At this point, the socket is simply a TCP/IP passthrough.
	$fp = $result["fp"];

	fwrite($fp, "CUSTOM PROTOCOL HERE\n");
	echo fgets($fp);
	sleep(1);

	fwrite($fp, "QUIT\n");
	echo fgets($fp);
	sleep(1);

	fclose($fp);
?>